PREFIX schema: <https://schema.org/>
PREFIX vdl: <https://w3id.org/vdl#>
PREFIX citizenship: <https://w3id.org/citizenship#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?s
WHERE {
  ?s citizenship:employmentAuthorizationDocument [ citizenship:lprCategory "C09" ] ;
    citizenship:residentSince ?date ;
    schema:birthDate ?birthDate ;
    vdl:license [ vdl:expiryDate ?expiryDate ] .

  # Has been a resident for at least 5 years
  FILTER( ?date < xsd:dateTime("2020-01-01T00:00:00") )

  # # Is over 18
  FILTER( ?birthDate < xsd:dateTime("2007-01-01T00:00:00") )

  # # License is valid
  FILTER( ?expiryDate > xsd:dateTime("2025-01-01T00:00:00") )
}
